// Package catalog is the embedded, offline snapshot of public ATS companies. It
// ships a gzipped ats,name,slug table (generated by internal/catalog/gen from the
// public jobhive companies CSV) and provides a stdlib fuzzy search over it, so
// `jl company search` surfaces candidates without any network call. The careers
// URL for a row is derived from its ATS and slug rather than stored, which keeps
// the artifact small; refresh it with `make catalog`.
package catalog

import (
	"bufio"
	"bytes"
	"compress/gzip"
	_ "embed"
	"sort"
	"strings"
	"sync"
)

//go:embed companies.csv.gz
var gzData []byte

// Company is one catalog row: an ATS, a display name, and the slug the scraper
// needs. The careers URL is not stored; URL() derives it.
type Company struct {
	ATS  string `json:"ats"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// URL derives a careers URL from the company's ATS and slug. It returns "" when
// the ATS is not one of the multi-tenant boards with a deterministic URL shape;
// callers show that as "(careers url unknown)".
func (c Company) URL() string { return URL(c.ATS, c.Slug) }

// URL reconstructs a careers URL from an ATS and slug. It is the single source of
// truth for url-from-ats-and-slug, shared by the catalog and the CLI's URL
// parser, and the reverse of the host table that parses careers URLs. An ATS this
// table does not know returns "".
func URL(ats, slug string) string {
	ats = strings.ToLower(strings.TrimSpace(ats))
	slug = strings.TrimSpace(slug)
	if ats == "" || slug == "" {
		return ""
	}
	switch ats {
	case "greenhouse":
		return "https://boards.greenhouse.io/" + slug
	case "ashby":
		return "https://jobs.ashbyhq.com/" + slug
	case "lever":
		return "https://jobs.lever.co/" + slug
	case "workable":
		return "https://apply.workable.com/" + slug
	case "smartrecruiters":
		return "https://jobs.smartrecruiters.com/" + slug
	case "recruitee":
		return "https://" + slug + ".recruitee.com"
	case "teamtailor":
		return "https://" + slug + ".teamtailor.com"
	default:
		return ""
	}
}

var (
	once    sync.Once
	loaded  []Company
	loadErr error
)

// load decompresses and parses the embedded table once, lazily. The artifact is a
// gzipped CSV-ish file of ats,name,slug rows (no header); names with commas are
// not expected in this data, but a safe split on the first two commas keeps any
// stray comma in the name intact.
func load() ([]Company, error) {
	once.Do(func() {
		gr, err := gzip.NewReader(bytes.NewReader(gzData))
		if err != nil {
			loadErr = err
			return
		}
		defer gr.Close()
		sc := bufio.NewScanner(gr)
		sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
		var out []Company
		for sc.Scan() {
			line := sc.Text()
			if line == "" {
				continue
			}
			i := strings.IndexByte(line, ',')
			if i < 0 {
				continue
			}
			ats := line[:i]
			rest := line[i+1:]
			j := strings.LastIndexByte(rest, ',')
			if j < 0 {
				continue
			}
			name := rest[:j]
			slug := rest[j+1:]
			out = append(out, Company{ATS: ats, Name: name, Slug: slug})
		}
		loadErr = sc.Err()
		loaded = out
	})
	return loaded, loadErr
}

// All returns the full decompressed catalog (lazily loaded). Callers must not
// mutate the returned slice.
func All() ([]Company, error) { return load() }

// Result is a ranked search hit.
type Result struct {
	Company
	score int
}

// Search ranks catalog companies by how well their name matches query, case
// insensitively. An exact name beats a prefix, which beats a word-boundary
// match, which beats a subsequence match; ties break toward the shorter name.
// Non-matching rows are dropped. If ats is non-empty, only rows with that ATS are
// considered. limit caps the result count (0 or negative means no cap).
func Search(query, ats string, limit int) ([]Result, error) {
	rows, err := load()
	if err != nil {
		return nil, err
	}
	return search(rows, query, ats, limit), nil
}

// search is the pure ranking core, factored out so tests can exercise it against
// a small fixture instead of the 40k embedded rows.
func search(rows []Company, query, ats string, limit int) []Result {
	q := strings.ToLower(strings.TrimSpace(query))
	atsFilter := strings.ToLower(strings.TrimSpace(ats))
	var hits []Result
	for _, c := range rows {
		if atsFilter != "" && strings.ToLower(c.ATS) != atsFilter {
			continue
		}
		if q == "" {
			// An empty query lists everything (filtered by ats), unranked.
			hits = append(hits, Result{Company: c, score: 0})
			continue
		}
		if s, ok := score(strings.ToLower(c.Name), q); ok {
			hits = append(hits, Result{Company: c, score: s})
		}
	}
	sort.SliceStable(hits, func(i, j int) bool {
		if hits[i].score != hits[j].score {
			return hits[i].score > hits[j].score // higher score first
		}
		if len(hits[i].Name) != len(hits[j].Name) {
			return len(hits[i].Name) < len(hits[j].Name) // shorter name first
		}
		return hits[i].Name < hits[j].Name // stable, deterministic tiebreak
	})
	if limit > 0 && len(hits) > limit {
		hits = hits[:limit]
	}
	return hits
}

// score rates how well a lowercased name matches a lowercased query, returning a
// score and whether it matched at all. Tiers, high to low: exact equality, name
// is a prefix of (or equals) the query target, a match at a word boundary, then a
// plain subsequence match anywhere. A non-subsequence is not a match.
func score(name, q string) (int, bool) {
	if name == q {
		return 1000, true
	}
	if strings.HasPrefix(name, q) {
		return 800, true
	}
	if i := strings.Index(name, q); i >= 0 {
		// A contiguous substring match; stronger if it starts a word.
		if i == 0 || isBoundary(name[i-1]) {
			return 700, true
		}
		return 600, true
	}
	if isSubsequence(name, q) {
		return 400, true
	}
	return 0, false
}

// isBoundary reports whether b separates words (so a match just after it counts
// as starting a word).
func isBoundary(b byte) bool {
	switch b {
	case ' ', '-', '_', '.', '/', '(', ')', ',', '&':
		return true
	}
	return false
}

// isSubsequence reports whether all bytes of q appear in s in order (not
// necessarily contiguously).
func isSubsequence(s, q string) bool {
	if q == "" {
		return true
	}
	qi := 0
	for i := 0; i < len(s) && qi < len(q); i++ {
		if s[i] == q[qi] {
			qi++
		}
	}
	return qi == len(q)
}
